language: objective-c
osx_image: xcode10
xcode_scheme: Jeni
xcode_project: Jeni.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X

branches:
 only:
 - master

before_install:
 - pod install
