language: objective-c
osx_image: xcode10
script:
    - xcodebuild clean test -project Jeni.xcodeproj -workspace Jeni.xcworkspace -scheme Jeni -destination "platform=iOS Simulator,name=iPhone 7,OS=10" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

branches:
 only:
 - master

before_install:
 - pod install
