language: swift

branches:
 only:
 - master

before_install:
 - rvm use system
 - sudo gem install cocoapods
 - pod install

xcode_project: Jeni.xcodeproj
xcode_scheme: Jeni
xcode_destination: platform=iOS Simulator
