os: osx
osx_image: xcode10.3
language: objective-c
script:
 - set -o pipefail && xcodebuild -workspace "Jeni.xcworkspace" -scheme "Jeni" -destination "platform=iOS Simulator,OS=12.4,name=iPhone 7" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
 
branches:
 only:
 - master
