default_platform(:ios)

platform :ios do
  desc "Sync signing"
  lane :signing do
    
  end

  desc "Build binary"
  lane :build do
    signing
  end

  desc "Release"
  lane :release do
    build
  end
end
